'use strict';
const T=require('./transactions');
const $=id=>document.getElementById(id),STORAGE='tru_hosted_swap_wallet_v1';
let config,wallet=null,password=null,quote=null,active=false,busy=false,lastUse=Date.now(),timer;
const random=()=>T.Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString('hex');
const message=s=>{$('message').textContent=s;};
const fmt=s=>{const n=BigInt(s);return (n/100000000n).toString()+'.'+(n%100000000n).toString().padStart(8,'0');};
function decimal(s){T.check(/^(0|[1-9][0-9]*)(\.[0-9]{1,8})?$/.test(s),'Enter a positive amount with up to eight decimals');const [a,b='']=s.split('.');return T.atoms((BigInt(a)*100000000n+BigInt(b.padEnd(8,'0'))).toString()).toString();}
function download(name,content){const url=URL.createObjectURL(new Blob([content],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);}
async function encryptionKey(pass,salt){const material=await crypto.subtle.importKey('raw',new TextEncoder().encode(pass),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:310000,hash:'SHA-256'},material,{name:'AES-GCM',length:256},false,['encrypt','decrypt']);}
async function encrypt(data,pass){const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await encryptionKey(pass,salt);const ciphertext=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode('TRU-HOSTED-WALLET-V1')},key,new TextEncoder().encode(JSON.stringify(data)));return JSON.stringify({format:'TRU-HOSTED-WALLET-V1',salt:T.Buffer.from(salt).toString('hex'),iv:T.Buffer.from(iv).toString('hex'),ciphertext:T.Buffer.from(ciphertext).toString('hex')});}
async function decrypt(text,pass){const e=JSON.parse(text);T.check(e.format==='TRU-HOSTED-WALLET-V1','Unsupported backup');T.hex(e.salt,16);T.hex(e.iv,12);T.hex(e.ciphertext);const key=await encryptionKey(pass,T.Buffer.from(e.salt,'hex'));const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:T.Buffer.from(e.iv,'hex'),additionalData:new TextEncoder().encode(e.format)},key,T.Buffer.from(e.ciphertext,'hex'));const w=JSON.parse(new TextDecoder().decode(plain));T.pubkey(w.key);T.check(w.swaps&&typeof w.swaps==='object','Invalid wallet backup');return w;}
async function save(){T.check(wallet&&password,'Unlock the wallet');const raw=await encrypt(wallet,password);localStorage.setItem(STORAGE,raw);return raw;}
async function backup(){download('TRU-swap-wallet-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json',await save());}
function lock(){wallet=null;password=null;active=false;quote=null;$('password').value='';$('wallet').hidden=true;$('locked').hidden=false;$('review').hidden=true;message('Wallet locked. The server continues monitoring. Unlock and resume to sign a pending claim.');}
async function api(path,payload={}){T.check(wallet,'Unlock your wallet');const url='/easy-swap/api/'+path,envelope={path:url,payload,time:Math.floor(Date.now()/1000),nonce:random()};const auth={pub:T.pubkey(wallet.key),time:envelope.time,nonce:envelope.nonce,signature:T.signDigest(T.requestDigest(envelope),wallet.key)};
  const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...payload,auth}),cache:'no-store',signal:AbortSignal.timeout(60000)});const r=await response.json();if(!response.ok)throw new Error(r.error||'Service unavailable');return r;}
async function unlocked(){lastUse=Date.now();$('create').hidden=true;$('unlock').hidden=false;$('locked').hidden=true;$('wallet').hidden=false;$('password').value='';await balance();await refreshSwaps();message('Wallet unlocked. Keep your encrypted backup safe.');}
async function balance(){const chain=$('balanceChain').value,pub=T.pubkey(wallet.key);$('address').value=T.address(pub,config.chains[chain].addressVersion);$('balance').textContent='Checking confirmed funds…';const {coins}=await api('balance',{chain});$('balance').textContent=fmt(coins.reduce((n,u)=>n+T.atoms(u.amount),0n))+' '+chain.toUpperCase()+' confirmed · network fee '+fmt(config.chains[chain].fundingFee);return coins;}
function validateQuote(r,local){
  const pub=T.pubkey(wallet.key);T.check(r.id===local.id&&r.user===pub&&r.operator===config.operator&&r.from===local.from&&r.to===local.to&&r.amount===local.amount&&r.hash===T.h160(local.secret),'Quote does not match your request');
  T.check(r.first.claim===config.operator&&r.first.refund===pub&&r.second.claim===pub&&r.second.refund===config.operator&&r.first.hash===r.hash&&r.second.hash===r.hash,'Contract roles changed');
  T.check(r.first.time-r.second.time>=21600&&r.second.time>=r.created+43200,'Unsafe refund deadlines');
  if(!local.record){T.check(r.fees.firstFunding===config.chains[r.from].fundingFee&&r.fees.firstExit===config.chains[r.from].exitFee&&r.fees.secondFunding===config.chains[r.to].fundingFee&&r.fees.secondExit===config.chains[r.to].exitFee,'Network fees changed');
  const rate=config.rates[r.from+':'+r.to];T.check(T.atoms(r.receive)===T.atoms(r.amount)*T.atoms(rate.numerator)/T.atoms(rate.denominator),'Quote rate changed');}
  const expected=T.funding(r.from,r.userCoins,r.first,r.amount,r.fees.firstFunding,pub);T.check(T.canonical(expected)===T.canonical(r.userPlan),'Funding plan changed');
  if(local.record){for(const k of ['first','second','userPlan','fees','ownCoins','userCoins','receive'])T.check(T.canonical(r[k])===T.canonical(local.record[k]),'Saved swap terms changed');}
}
function addTerm(name,value){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=name;dd.textContent=value;$('terms').append(dt,dd);}
async function getQuote(){const from=$('from').value,to=$('to').value;T.check(from!==to&&(from==='tru'||to==='tru'),'Choose TRU and BSV, or TRU and BSTY');const local={id:random(),from,to,amount:decimal($('amount').value.trim()),secret:random()};const r=await api('quote',{from,to,amount:local.amount,hash:T.h160(local.secret),requestId:local.id});validateQuote(r,local);local.record=r;wallet.swaps[r.id]=local;await save();quote=r;$('terms').replaceChildren();addTerm('You send',fmt(r.amount)+' '+from.toUpperCase());addTerm('Funding network fee',fmt(r.fees.firstFunding)+' '+from.toUpperCase());addTerm('You receive, after claim fee',fmt((T.atoms(r.receive)-T.atoms(r.fees.secondExit)).toString())+' '+to.toUpperCase());addTerm('Your refund becomes available',new Date(r.first.time*1000).toLocaleString()+' (chain time)');addTerm('Quote expires',new Date(r.expires*1000).toLocaleTimeString());$('review').hidden=false;message('Review the amounts, then confirm.');}
async function confirmSwap(){T.check(quote,'Get a quote first');const r=quote,local=wallet.swaps[r.id];validateQuote(r,local);T.check(Date.now()/1000<r.expires,'Quote expired; request a new quote');
  const raw=T.signFunding(r.from,r.userPlan,r.userCoins,wallet.key),id=T.txid(r.from,raw);const refund=T.signExit(r.from,T.exit(r.from,id,r.first,r.amount,r.fees.firstExit,r.user,true),r.first,r.amount,wallet.key);
  local.funding=raw;local.refund=refund;local.approved=true;await backup();active=true;
  message('Recovery backup downloaded. Submitting your signed funding transaction…');local.record=await api('fund',{id:r.id,raw,refund});await save();$('review').hidden=true;quote=null;await refreshSwaps();}
const labels={QUOTED:'Quote ready',EXPIRED:'Quote expired',FUNDING:'Waiting for your funding confirmations',COUNTER_FUNDING:'Waiting for the receiving chain',READY_TO_CLAIM:'Ready to receive your coins',CLAIMING:'Claim submitted — waiting for confirmations',COMPLETE:'Swap complete',REFUNDING:'Refund in progress',REFUNDED:'Refund confirmed'};
async function refreshSwaps(){if(!wallet)return;const records=await api('swaps');$('swaps').replaceChildren();for(const r of records){const local=wallet.swaps[r.id];const card=document.createElement('div');card.className='swap';const title=document.createElement('strong');title.textContent=fmt(r.amount)+' '+r.from.toUpperCase()+' → '+fmt((T.atoms(r.receive)-T.atoms(r.fees.secondExit)).toString())+' '+r.to.toUpperCase();const status=document.createElement('p');status.textContent=labels[r.state]||r.state;const detail=document.createElement('p');detail.textContent='Funding confirmations: '+(r.firstConfirmations||0)+' / '+config.chains[r.from].confirmations+' · Receiving chain: '+(r.secondConfirmations||0)+' / '+config.chains[r.to].confirmations;const id=document.createElement('code');id.textContent=r.id;card.append(title,status,detail,id);
    if(r.notice||r.error){const warning=document.createElement('p');warning.textContent=r.notice||r.error;card.append(warning);}
    if(local?.refund){const button=document.createElement('button');button.className='secondary';button.textContent='Download refund transaction';button.onclick=()=>download('TRU-swap-refund-'+r.id+'.json',JSON.stringify({format:'TRU-SWAP-REFUND-V1',chain:r.from,refundTime:r.first.time,raw:local.refund,txid:T.txid(r.from,local.refund),note:'Broadcast with your own node after chain median time passes refundTime. No password or secret is included.'},null,2));card.append(button);}
    if(!local){const note=document.createElement('p');note.textContent='Restore the backup made for this swap to recover its secret.';card.append(note);}
    $('swaps').append(card);
    if(local){validateQuote(r,local);local.record=r;}
    if(local?.approved&&active&&r.state==='QUOTED'&&local.funding){await api('fund',{id:r.id,raw:local.funding,refund:local.refund});}
    if(local?.approved&&active&&r.state==='READY_TO_CLAIM'){
      T.check(r.firstConfirmations>=config.chains[r.from].confirmations&&r.secondConfirmations>=config.chains[r.to].confirmations,'Waiting for confirmations');
      const counter=T.funding(r.to,r.ownCoins,r.second,r.receive,r.fees.secondFunding,r.operator);T.verifyFunding(r.to,r.ownFunding,counter,r.ownCoins,r.operator);T.check(T.txid(r.to,r.ownFunding)===r.ownFundingId,'Counter-funding ID mismatch');
      const claim=T.signExit(r.to,T.exit(r.to,r.ownFundingId,r.second,r.receive,r.fees.secondExit,r.user),r.second,r.receive,wallet.key,local.secret);local.claim=claim;await save();await api('claim',{id:r.id,raw:claim});message('Claim signed and submitted. The server will monitor settlement.');
    }
  }await save();}
async function withdraw(){const chain=$('balanceChain').value,payload=T.bsv.encoding.Base58Check.decode($('destination').value.trim());T.check(payload.length===21&&payload[0]===config.chains[chain].addressVersion,'Destination is not a standard address on the selected network');const {coins:all}=await api('balance',{chain});const records=await api('swaps'),reserved=new Set(records.filter(r=>r.state!=='EXPIRED').flatMap(r=>r.from===chain?r.userCoins.map(u=>u.txid+':'+u.vout):[]));const coins=all.filter(u=>!reserved.has(u.txid+':'+u.vout));const fee=T.atoms(config.chains[chain].fundingFee),value=coins.reduce((n,u)=>n+T.atoms(u.amount),0n)-fee;T.check(value>=546n,'No available balance after fees');T.check(confirm('Send '+fmt(value.toString())+' '+chain.toUpperCase()+' to '+$('destination').value.trim()+'? Network fee: '+fmt(fee.toString())), 'Withdrawal cancelled');const tx={version:1,inputs:coins.map(u=>({txid:u.txid,vout:u.vout,sequence:0xffffffff,script:''})),outputs:[{amount:value.toString(),script:'76a914'+payload.subarray(1).toString('hex')+'88ac'}],locktime:0};const raw=T.signFunding(chain,tx,coins,wallet.key);wallet.lastWithdrawal={chain,raw};await save();const r=await api('withdraw',{chain,raw});message('Withdrawal submitted: '+r.txid);await balance();}
function action(fn){return async()=>{if(busy)return;busy=true;lastUse=Date.now();for(const b of document.querySelectorAll('button'))b.disabled=true;try{await fn();}catch(e){message(e.message);}finally{busy=false;for(const b of document.querySelectorAll('button'))b.disabled=false;}};}
async function boot(){T.check(window.isSecureContext&&crypto.subtle,'Open this wallet over HTTPS or localhost');config=await (await fetch('api/config',{cache:'no-store'})).json();T.check(config.protocol==='TRU-HOSTED-SWAP-V1','Wrong swap service');$('connection').textContent=config.enabled?'Service connected':'New swaps paused';$('create').hidden=!!localStorage.getItem(STORAGE);$('unlock').hidden=!localStorage.getItem(STORAGE);
  $('create').onclick=action(async()=>{T.check(!localStorage.getItem(STORAGE),'A wallet already exists; back it up first');password=$('password').value;T.check(password.length>=12,'Use at least 12 characters');wallet={key:random(),swaps:{},created:new Date().toISOString()};await backup();await unlocked();});
  $('unlock').onclick=action(async()=>{const pass=$('password').value;const w=await decrypt(localStorage.getItem(STORAGE),pass);wallet=w;password=pass;await unlocked();});
  $('restore').onchange=action(async()=>{const file=$('restore').files[0];T.check(file&&file.size<10000000,'Invalid backup file');const pass=$('password').value,w=await decrypt(await file.text(),pass);if(localStorage.getItem(STORAGE))T.check(confirm('Replace this browser’s saved wallet? Download its backup first.'),'Restore cancelled');wallet=w;password=pass;await save();await unlocked();});
  $('backup').onclick=action(backup);$('lock').onclick=lock;$('refresh').onclick=action(balance);$('balanceChain').onchange=action(balance);$('withdraw').onclick=action(withdraw);$('quote').onclick=action(getQuote);$('confirm').onclick=action(confirmSwap);$('reverse').onclick=()=>{const v=$('from').value;$('from').value=$('to').value;$('to').value=v;};$('resume').onclick=action(async()=>{active=true;await refreshSwaps();message('Signing resumed for swaps you already approved.');});
  timer=setInterval(async()=>{if(wallet&&Date.now()-lastUse>15*60*1000){lock();return;}if(wallet&&!busy){busy=true;try{await refreshSwaps();}catch(e){message(e.message);}finally{busy=false;}}},15000);
}
boot().catch(e=>message(e.message));
