'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const T=require('../src/transactions'),{Store}=require('../src/store'),{Coordinator}=require('../src/coordinator'),{authenticate}=require('../src/server');
const key='01'.padStart(64,'0'),operatorKey='02'.padStart(64,'0'),user=T.pubkey(key),operator=T.pubkey(operatorKey),secret='ab'.repeat(32);
class FakeChain {
 constructor(name){this.name=name;this.utxos=new Map();this.txs=new Map();this.clock=Math.floor(Date.now()/1000);this.broadcasts=[];}
 async tip(){return {height:20000,time:this.clock,mtp:this.clock,hash:'ff'.repeat(32)};}
 async coins(pub){return [...this.utxos.values()].filter(x=>x.script===T.p2pkh(pub));}
 async outpoint(id,n){return this.utxos.get(id+':'+n)||null;}
 async status(id){return this.txs.get(id)||{known:false,confirmations:0};}
 async broadcast(raw){const id=T.txid(this.name,raw);if((await this.status(id)).known)return id;const tx=T.parse(this.name,raw);assert(tx.locktime<this.clock||tx.inputs.every(i=>i.sequence===0xffffffff),'non-final transaction');for(const i of tx.inputs)assert(this.utxos.has(i.txid+':'+i.vout),'input missing');for(const i of tx.inputs)this.utxos.delete(i.txid+':'+i.vout);tx.outputs.forEach((o,vout)=>this.utxos.set(id+':'+vout,{txid:id,vout,...o,confirmations:0}));this.txs.set(id,{known:true,confirmations:0,raw});this.broadcasts.push(raw);return id;}
 confirm(){for(const s of this.txs.values())s.confirmations=6;for(const u of this.utxos.values())u.confirmations=6;}
 seed(pub,id){this.utxos.set(id+':0',{txid:id,vout:0,amount:'50000000',script:T.p2pkh(pub),confirmations:6});}
 async findSpend(id,vout){for(const [hash,s]of this.txs)if(T.parse(this.name,s.raw).inputs.some(i=>i.txid===id&&i.vout===vout))return {...s,id:hash};return null;}
}
function setup(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tru-swap-test-')),db=path.join(dir,'test.sqlite'),store=new Store(db),chains={};for(const n of ['tru','bsv','bsty']){chains[n]=new FakeChain(n);chains[n].seed(user,'11'.repeat(32));chains[n].seed(operator,'22'.repeat(32));}
 const config={enabled:true,maxActive:100,maxTipAge:3600,firstSeconds:172800,secondSeconds:86400,claimSafetySeconds:3600,counterFundingSafetySeconds:21600,chains:Object.fromEntries(Object.keys(chains).map(n=>[n,{addressVersion:n==='tru'?65:0,confirmations:2,fundingFee:'10000',exitFee:'10000'}])),rates:Object.fromEntries(['tru:bsv','bsv:tru','tru:bsty','bsty:tru'].map(p=>[p,{enabled:true,numerator:'1',denominator:'1',minAtoms:'100000',maxAtoms:'10000000'}]))};return {dir,db,store,chains,config,c:new Coordinator(config,store,chains,operatorKey)};}
async function funded(x,from,to){const r=await x.c.quote(user,{from,to,amount:'1000000',hash:T.h160(secret),requestId:'aa'.repeat(32)});const raw=T.signFunding(from,r.userPlan,r.userCoins,key),refund=T.signExit(from,T.exit(from,T.txid(from,raw),r.first,r.amount,r.fees.firstExit,user,true),r.first,r.amount,key);await x.c.submitFunding(user,{id:r.id,raw,refund});return x.store.get(r.id);}
for(const [from,to] of [['tru','bsv'],['bsv','tru'],['tru','bsty'],['bsty','tru']])test(from+' -> '+to+': complete flow, restart, duplicate submit and confirmed-only completion',async()=>{
 const x=setup();try{let r=await funded(x,from,to);assert.equal(r.state,'FUNDING');await x.c.tick();assert.equal(x.store.get(r.id).ownFunding,undefined);x.chains[from].confirm();await x.c.tick();r=x.store.get(r.id);assert(r.ownFunding);assert.equal(x.chains[to].broadcasts.length,1);x.store.close();x.store=new Store(x.db);x.c=new Coordinator(x.config,x.store,x.chains,operatorKey);await x.c.tick();assert.equal(x.chains[to].broadcasts.length,1);x.chains[to].confirm();await x.c.tick();r=x.store.get(r.id);assert.equal(r.state,'READY_TO_CLAIM');const raw=T.signExit(to,T.exit(to,r.ownFundingId,r.second,r.receive,r.fees.secondExit,user),r.second,r.receive,key,secret);await x.c.claim(user,{id:r.id,raw});await x.c.tick();assert.equal(x.store.get(r.id).state,'CLAIMING');x.chains[from].confirm();x.chains[to].confirm();await x.c.tick();r=x.store.get(r.id);assert.equal(r.state,'COMPLETE');assert(r.settledAt);await x.c.submitFunding(user,{id:r.id,raw:r.userFunding,refund:r.userRefund});assert.equal(x.chains[from].broadcasts.length,2);
 }finally{x.store.close();fs.rmSync(x.dir,{recursive:true,force:true});}
});
test('Timeout refunds both sides with browser offline',async()=>{const x=setup();try{let r=await funded(x,'tru','bsv');x.chains.tru.confirm();await x.c.tick();x.chains.bsv.confirm();x.chains.bsv.clock=r.second.time+1;await x.c.tick();r=x.store.get(r.id);assert(r.ownRefundBroadcast);x.chains.tru.clock=r.first.time+1;await x.c.tick();x.chains.tru.confirm();x.chains.bsv.confirm();await x.c.tick();assert.equal(x.store.get(r.id).state,'REFUNDED');}finally{x.store.close();fs.rmSync(x.dir,{recursive:true,force:true});}});
test('Funding rollback pauses claim and never duplicates operator funding',async()=>{const x=setup();try{let r=await funded(x,'tru','bsv');x.chains.tru.confirm();await x.c.tick();x.chains.bsv.confirm();await x.c.tick();r=x.store.get(r.id);x.chains.tru.txs.get(r.userFundingId).confirmations=0;const raw=T.signExit('bsv',T.exit('bsv',r.ownFundingId,r.second,r.receive,r.fees.secondExit,user),r.second,r.receive,key,secret);await assert.rejects(()=>x.c.claim(user,{id:r.id,raw}),/confirmed/);await x.c.tick();assert.equal(x.chains.bsv.broadcasts.length,1);assert(x.store.get(r.id).notice);}finally{x.store.close();fs.rmSync(x.dir,{recursive:true,force:true});}});
test('Authorization binds path/body/owner and rejects durable nonce replay',()=>{const x=setup();try{const payload={id:'aa'.repeat(32)},path='/easy-swap/api/swap',time=Math.floor(Date.now()/1000),nonce='bb'.repeat(32),signature=T.signDigest(T.requestDigest({path,payload,time,nonce}),key),body={...payload,auth:{pub:user,time,nonce,signature}};assert.equal(authenticate(x.store,path,body).user,user);assert.throws(()=>authenticate(x.store,path,body));assert.throws(()=>authenticate(x.store,path,{...body,id:'cc'.repeat(32)}));assert.throws(()=>x.c.owned(operator,'aa'.repeat(32)));}finally{x.store.close();fs.rmSync(x.dir,{recursive:true,force:true});}});
test('Persisted funding survives an ambiguous broadcast failure',async()=>{const x=setup();try{const original=x.chains.tru.broadcast.bind(x.chains.tru);let first=true;x.chains.tru.broadcast=async raw=>{if(first){first=false;throw new Error('connection lost');}return original(raw);};await assert.rejects(()=>funded(x,'tru','bsv'),/connection lost/);const r=x.store.get('aa'.repeat(32));assert(r.userFunding&&r.userRefund);await x.c.tick();assert.equal(x.chains.tru.broadcasts.length,1);}finally{x.store.close();fs.rmSync(x.dir,{recursive:true,force:true});}});
