'use strict';
// Offline: decrypt backup and export a signed refund/claim. Never broadcasts.
const fs=require('node:fs'),crypto=require('node:crypto'),T=require('../src/transactions');
async function password(){if(!process.stdin.isTTY)return fs.readFileSync(0,'utf8').trimEnd();process.stderr.write('Backup password (hidden): ');process.stdin.setRawMode(true);process.stdin.resume();return await new Promise((resolve,reject)=>{let value='';const onData=b=>{for(const c of b.toString()){if(c==='\u0003'){process.stdin.setRawMode(false);process.stdin.pause();reject(new Error('Cancelled'));return;}if(c==='\r'||c==='\n'){process.stdin.setRawMode(false);process.stdin.pause();process.stdin.off('data',onData);process.stderr.write('\n');resolve(value);return;}if(c==='\u007f')value=value.slice(0,-1);else value+=c;}};process.stdin.on('data',onData);});}
async function main(){const [file,id,action,fundingFile]=process.argv.slice(2);T.check(file&&id&&['refund','claim'].includes(action),'Usage: node tools/recover.js BACKUP.json SWAP_ID refund|claim [CONFIRMED_FUNDING_RAW_FILE]');
 const e=JSON.parse(fs.readFileSync(file,'utf8'));T.check(e.format==='TRU-HOSTED-WALLET-V1','Wrong backup format');T.hex(e.salt,16);T.hex(e.iv,12);T.hex(e.ciphertext);const key=crypto.pbkdf2Sync(await password(),Buffer.from(e.salt,'hex'),310000,32,'sha256'),bytes=Buffer.from(e.ciphertext,'hex'),d=crypto.createDecipheriv('aes-256-gcm',key,Buffer.from(e.iv,'hex'));d.setAAD(Buffer.from(e.format));d.setAuthTag(bytes.subarray(-16));const wallet=JSON.parse(Buffer.concat([d.update(bytes.subarray(0,-16)),d.final()]).toString('utf8'));const local=wallet.swaps[id];T.check(local,'Swap is absent from this backup');const r=local.record,refund=action==='refund',chain=refund?r.from:r.to,c=refund?r.first:r.second,amount=refund?r.amount:r.receive,fee=refund?r.fees.firstExit:r.fees.secondExit;
 const funding=fundingFile?fs.readFileSync(fundingFile,'utf8').trim():refund?(local.funding||r.userFunding):r.ownFunding;T.check(funding,'Supply the confirmed counter-funding raw transaction file');
 const plan=refund?r.userPlan:T.funding(chain,r.ownCoins,c,amount,r.fees.secondFunding,r.operator);T.check(T.sameIntent(chain,funding,plan),'Funding transaction does not match saved swap terms');const fundingId=T.txid(chain,funding),raw=T.signExit(chain,T.exit(chain,fundingId,c,amount,fee,r.user,refund),c,amount,wallet.key,refund?null:local.secret);
 const name='recovery-'+id+'-'+action+'.json';fs.writeFileSync(name,JSON.stringify({format:'TRU-SWAP-RECOVERY-V1',chain,action,refundTime:refund?c.time:null,fundingTxid:fundingId,txid:T.txid(chain,raw),raw},null,2),{flag:'wx',mode:0o600});console.log('Created '+name+'. Verify the funding transaction on the active chain before revealing a claim secret. Refunds require chain time to pass the saved deadline. No broadcast performed.');}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
