# GUI-DESKTOP-01: include this from the clean repository root CMakeLists.txt.
# Preserves its source list, options, lineage and production/test targets.
if(BUILD_WITH_QT)
    find_package(Qt5 5.12 REQUIRED COMPONENTS Widgets Network)
    foreach(_tru_target tru_advanced tru_evolve_token tru_miner tru_miner_cpu tru_wallet blockexplorer)
        if(TARGET ${_tru_target})
            get_target_property(_tru_sources ${_tru_target} SOURCES)
            foreach(_tru_gui_source walletgui.cpp desktop_panel.cpp desktop_rpc.cpp)
                set(_tru_present FALSE)
                foreach(_tru_source IN LISTS _tru_sources)
                    get_filename_component(_tru_name "${_tru_source}" NAME)
                    if(_tru_name STREQUAL _tru_gui_source)
                        set(_tru_present TRUE)
                    endif()
                endforeach()
                if(NOT _tru_present)
                    target_sources(${_tru_target} PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/${_tru_gui_source}")
                endif()
            endforeach()
            target_sources(${_tru_target} PRIVATE "${CMAKE_CURRENT_LIST_DIR}/../src/walletgui.h")
            target_compile_definitions(${_tru_target} PRIVATE BUILD_WITH_QT)
            target_link_libraries(${_tru_target} PRIVATE Qt5::Widgets Qt5::Network)
            set_target_properties(${_tru_target} PROPERTIES AUTOMOC ON)
        endif()
    endforeach()
endif()
